-- MIG-007 / M2-P007: independent material and initial-price review roles.
ALTER TABLE `approval_task`
  MODIFY `approval_type` ENUM('SUPPLIER_ONBOARDING', 'FUNCTIONAL_ACCOUNT_CHANGE', 'SENSITIVE_EXPORT', 'SUPPLIER_SENSITIVE_CHANGE', 'PRODUCT_MATERIAL', 'PRODUCT_INITIAL_PRICE') NOT NULL,
  MODIFY `assigned_account_type_code` ENUM('COMPANY_SUPPLIER_OPS', 'COMPANY_SUPER_ADMIN', 'COMPANY_AUDIT', 'SUPPLIER_ACCOUNT_ADMIN', 'COMPANY_PRODUCT_OPS', 'COMPANY_PRICE_REVIEW') NOT NULL;
